// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || SUPABASE_URL.includes('your-project-id')) {
  console.error('❌ Missing or invalid VITE_SUPABASE_URL');
  console.error('Please set VITE_SUPABASE_URL in your .env file');
  console.error('Get your Supabase URL from: https://supabase.com/dashboard > Project Settings > API');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.includes('your-anon-key')) {
  console.error('❌ Missing or invalid VITE_SUPABASE_PUBLISHABLE_KEY');
  console.error('Please set VITE_SUPABASE_PUBLISHABLE_KEY in your .env file');
  console.error('Get your Supabase key from: https://supabase.com/dashboard > Project Settings > API');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);